### ISSUE TITLE
#4: Write C code

### ISSUE THREAD

**Issue by 11551107C1** [csci3250-2019/project-team-d#12]
Please start to remember what you have done for C class. Or learn it anew.

Your tasks:

In code.c, write a piece of very simple (yet correct) C code (e.g. Hello World, simple for loop, simple if...then...else, etc.)
In readme.md, include your code (either copy & paste or include_relative)
Read this article to see how to get the GitHub shield for Travis CI, and put it inside readme.md with your code: https://hackernoon.com/continuous-integration-using-travis-on-github-1f7f2314b6b7
(Note: Travis CI is already installed on this repo)

**Comment by 11551107C1** [comment]
Please start to remember what you have done for C class. Or learn it anew.

Your tasks:

In code.c, write a piece of very simple (yet correct) C code (e.g. Hello World, simple for loop, simple if...then...else, etc.)
In readme.md, include your code (either copy & paste or include_relative)
Read this article to see how to get the GitHub shield for Travis CI, and put it inside readme.md with your code: https://hackernoon.com/continuous-integration-using-travis-on-github-1f7f2314b6b7
(Note: Travis CI is already installed on this repo)

**Comment by Huzo** [comment]
Is this part done guys, seems like we have the thing visible in README? I am not entirely sure if we have fulfilled it. @iPhoneL @11551107C1

**Comment by iPhoneL** [comment]
> Is this part done guys, seems like we have the thing visible in README? I am not entirely sure if we have fulfilled it. @iPhoneL @11551107C1

Yes this part is done, but you can add your code to code.c if you like.
