### ISSUE TITLE
#5: Promote your repo

### ISSUE THREAD

**Issue by ic17** [csci3250-2019/project-team-d#19]
# #5: Promote your repo

Now that your team has finished most of the tasks, you have to promote it! Your tasks:

1. Look at your team's page here: `https://csci3250-2019.github.io/(repo name)`
2. Go to the public repo of **`csci3250-2019.github.io`** in the CSCI3250 organization
3. Edit the file to add a link of your team, and request for review from @chuckjee

And there you're done!

**Comment by Huzo** [comment]
Hey guys, are we done with this? @SsparKluo @ic17 @iPhoneL @jkleung24 :)

**Comment by SsparKluo** [comment]
> Hey guys, are we done with this? @SsparKluo @ic17 @iPhoneL @jkleung24 :)

I guess not? Maybe we should rewrite our introduction and update the status of task list :p?

**Comment by DinethP** [comment]
@SsparKluo @ic17 @iPhoneL @jkleung24 Guys, in the public repo, when we click Team D, it gets redirected to Team C. Please fix this issue.

**Comment by iPhoneL** [comment]
> @SsparKluo @ic17 @iPhoneL @jkleung24 Guys, in the public repo, when we click Team D, it gets redirected to Team C. Please fix this issue.
OK

**Comment by DinethP** [comment]
@iPhoneL , the link now works properly, however, there seems to be spacing issues in the contributors page. Could you fix that so that we can then close this issue?

Thanks!

**Comment by iPhoneL** [comment]
> @iPhoneL , the link now works properly, however, there seems to be spacing issues in the contributors page. Could you fix that so that we can then close this issue?
> 
> Thanks!

Easy, you can fix it by adding an extra line to your /_stu/sid.md (simply tap enter at the end), I see everyone's sid.md is two line so that's why we got spacing issue. Since the sid.md is not mine, so you may need to modify by yourself, I'll approve your pull request ASAP.

**Comment by 11551107C1** [comment]
Seems that only @DinethP 's line have spacing issues now? Maybe after him/her finished editing we can finish our project?

**Comment by 11551107C1** [comment]
Then I think this issue is done?
Thxxx everybody:)

**Comment by DinethP** [comment]
Oh wait, the Task 5 checkbox is still not ticked
