### ISSUE TITLE
It seems that 1155108467 1155108852 1155110464 forgot to include themselves in readme.md?

### ISSUE THREAD

**Issue by andywaycuhk** [csci3250-2019/project-team-d#57]

**Comment by Huzo** [comment]
Yes, seems so. Can they add themselves by having pull requests? :) So that we all fulfill requirements :D

**Comment by andywaycuhk** [comment]
I also want to do so. Let's get it.

**Comment by andywaycuhk** [comment]
> Yes, seems so. Can they add themselves by having pull requests? :) So that we all fulfill requirements :D

Hey Huzo, I have included for them, could you please help review my request? Thanks:)

**Comment by DinethP** [comment]
@Huzo had reviewed the request and I just merged it now. Does that mean we are done with the project?

**Comment by andywaycuhk** [comment]
Thanks for your help. I'm also not quite sure, maybe we have finished it(?

**Comment by Huzo** [comment]
Looking at https://csci3250-2019.github.io/project-team-d/ seems good :D. Closing this issue since @DinethP merged the required changes.
