### ISSUE TITLE
#3: Project board

### ISSUE THREAD

**Issue by KanaCS** [csci3250-2019/project-team-d#7]
Please explore the Projects tab

Your tasks:

Create a new project board (with any name), and use the Basic Kanban template, containing "To do", "In Progress", and "Done"
Set up these automations:
When pull requests are added, put the item in "In progress"
When issues are closed, put the item in "Done"
When pull requests are merged, put the item in "Done"
Regularly visit the Issues and Pull requests tabs to make sure all items are marked with your project board

**Comment by Huzo** [comment]
[Done.](https://github.com/orgs/csci3250-2019/projects/2)

**Comment by Huzo** [comment]
@SsparKluo @KanaCS can you guys double check and see if it is done?  
Thanks.
